# docker-compose.yml
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: faas
      POSTGRES_PASSWORD: faaspass
      POSTGRES_DB: cofrap
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./pg-init:/docker-entrypoint-initdb.d
    ports: ["5432:5432"]

  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: cofrap
      DB_USER: faas
      DB_PASS: faaspass
    ports: ["8000:8000"]
    depends_on: [db]

volumes:
  pg-data:
